"use client";

import { useEffect, useRef } from "react";
import { EditorContent } from "@tiptap/react";
import { useCoverLetterEditor } from "../editor/tiptap-cover-letter-config";
import { useCoverLetterStore } from "../store/cover-letter-store";
import { DefaultCard } from "@/components/cards/default-card";
import { Button } from "@/components/base/buttons/button";
import { MagicWand01, RefreshCw01, AlertCircle } from "@untitledui/icons";
import { CoverLetterFormattingToolbar } from "./cover-letter-formatting-toolbar";
import "../editor/cover-letter-editor.css";

interface CoverLetterEditorProps {
    jobId: string;
    viewMode: "preview" | "edit";
    onRequestNew?: () => void;
    /** Ref forwarded to the white paper card for PDF capture */
    paperRef?: React.RefObject<HTMLDivElement | null>;
    /** True while an existing document is being fetched from Firestore */
    isLoadingDoc?: boolean;
}

// ─── Loading skeleton ─────────────────────────────────────────────────────────

function GeneratingSkeleton() {
    return (
        <div className="flex flex-col gap-5 p-8 animate-pulse" aria-label="Generating cover letter…">
            <div className="h-4 bg-secondary rounded-full w-3/4" />
            <div className="flex flex-col gap-3">
                <div className="h-3.5 bg-secondary rounded-full w-full" />
                <div className="h-3.5 bg-secondary rounded-full w-full" />
                <div className="h-3.5 bg-secondary rounded-full w-5/6" />
                <div className="h-3.5 bg-secondary rounded-full w-4/5" />
            </div>
            <div className="flex flex-col gap-3">
                <div className="h-3.5 bg-secondary rounded-full w-full" />
                <div className="h-3.5 bg-secondary rounded-full w-11/12" />
                <div className="h-3.5 bg-secondary rounded-full w-full" />
                <div className="h-3.5 bg-secondary rounded-full w-3/4" />
            </div>
            <div className="flex flex-col gap-3">
                <div className="h-3.5 bg-secondary rounded-full w-full" />
                <div className="h-3.5 bg-secondary rounded-full w-5/6" />
                <div className="h-3.5 bg-secondary rounded-full w-2/3" />
            </div>
            <div className="h-4 bg-secondary rounded-full w-1/3 mt-2" />
            <div className="flex items-center gap-2 mt-4 pt-4 border-t border-secondary">
                <MagicWand01 className="size-4 text-fg-brand-primary animate-pulse" />
                <p className="text-sm text-tertiary">Crafting your personalised cover letter…</p>
            </div>
        </div>
    );
}

// ─── Empty / pre-generation state ─────────────────────────────────────────────

function EmptyState({ onRequestNew }: { onRequestNew?: () => void }) {
    return (
        <div className="flex flex-col items-center justify-center h-full gap-6 p-8 text-center">
            <div className="flex items-center justify-center size-14 rounded-2xl bg-brand-50">
                <MagicWand01 className="size-7 text-fg-brand-primary" />
            </div>
            <div className="flex flex-col gap-2 max-w-sm">
                <h3 className="text-base font-semibold text-primary">Create your cover letter</h3>
                <p className="text-sm text-tertiary leading-relaxed">
                    Tell us about the role and your background. We'll craft a specific, human-sounding
                    letter that doesn't read like it was generated by an AI.
                </p>
            </div>
            {onRequestNew && (
                <Button size="md" color="primary" iconLeading={MagicWand01} onClick={onRequestNew}>
                    Get started
                </Button>
            )}
        </div>
    );
}

// ─── Error state ──────────────────────────────────────────────────────────────

function ErrorState({ error, onRetry }: { error: string; onRetry?: () => void }) {
    return (
        <div className="flex flex-col items-center justify-center h-full gap-6 p-8 text-center">
            <div className="flex items-center justify-center size-14 rounded-2xl bg-error-50">
                <AlertCircle className="size-7 text-error-primary" />
            </div>
            <div className="flex flex-col gap-2 max-w-sm">
                <h3 className="text-base font-semibold text-primary">Generation failed</h3>
                <p className="text-sm text-tertiary leading-relaxed">{error}</p>
            </div>
            {onRetry && (
                <Button size="md" color="secondary" iconLeading={RefreshCw01} onClick={onRetry}>
                    Try again
                </Button>
            )}
        </div>
    );
}

// ─── Main editor ──────────────────────────────────────────────────────────────

export function CoverLetterEditor({ jobId, viewMode, onRequestNew, paperRef, isLoadingDoc }: CoverLetterEditorProps) {
    const containerRef = useRef<HTMLDivElement>(null);
    const document = useCoverLetterStore((s) => s.document);
    const isGenerating = useCoverLetterStore((s) => s.isGenerating);
    const generationError = useCoverLetterStore((s) => s.generationError);
    const setShowInfoModal = useCoverLetterStore((s) => s.setShowInfoModal);
    const setContent = useCoverLetterStore((s) => s.setContent);
    const content = document?.content ?? "";

    const editor = useCoverLetterEditor(content, {
        editable: viewMode === "edit" && !isGenerating,
        onUpdate: (html) => setContent(html),
        documentId: document?.id,
    });

    // Sync editor content when generation completes (new content arrives)
    useEffect(() => {
        if (editor && document?.content && !isGenerating) {
            const current = editor.getHTML();
            if (current !== document.content) {
                editor.commands.setContent(document.content, { emitUpdate: false });
            }
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [document?.id, document?.content, isGenerating]);

    useEffect(() => {
        if (editor) {
            editor.setEditable(viewMode === "edit" && !isGenerating);
        }
    }, [editor, viewMode, isGenerating]);

    // ── Error state ──
    if (generationError) {
        return (
            <div className="flex h-full items-center justify-center p-8">
                <ErrorState
                    error={generationError}
                    onRetry={() => setShowInfoModal(true)}
                />
            </div>
        );
    }

    // ── Loading an existing document from Firestore ──
    if (isLoadingDoc) {
        return (
            <div className="flex-1 p-6 bg-primary overflow-y-auto">
                <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-sm border border-secondary">
                    <GeneratingSkeleton />
                </div>
            </div>
        );
    }

    // ── No document yet and not generating — show empty state ──
    if (!document && !isGenerating) {
        return <EmptyState onRequestNew={onRequestNew} />;
    }

    return (
        <div ref={containerRef} className="flex flex-col h-full overflow-y-auto">
            {/* Floating vertical toolbar — only visible in edit mode */}
            {viewMode === "edit" && !isGenerating && (
                <CoverLetterFormattingToolbar editor={editor} containerRef={containerRef} />
            )}

            <div className="flex-1 p-6 bg-primary">
                <DefaultCard
                    cardClassName="max-w-4xl mx-auto bg-white rounded-lg shadow-sm border border-secondary relative"
                    childProp={
                        isGenerating ? (
                            <GeneratingSkeleton />
                        ) : (
                            <div
                                ref={paperRef}
                                className="flex flex-col gap-6 p-8"
                                style={{
                                    fontFamily: "Times New Roman, serif",
                                    fontSize: "11pt",
                                }}
                            >
                                <EditorContent editor={editor} />
                            </div>
                        )
                    }
                />
            </div>

            {/* Regenerate button — visible once a letter exists */}
            {document && !isGenerating && onRequestNew && (
                <div className="shrink-0 flex justify-center pb-6">
                    <Button
                        size="sm"
                        color="secondary"
                        iconLeading={RefreshCw01}
                        onClick={onRequestNew}
                    >
                        Regenerate letter
                    </Button>
                </div>
            )}
        </div>
    );
}
